# Normally assigned swap size is two times of memory, but this is high for a default t2.micro with 8Gb disk
- name: set swap_space variable
  set_fact:
    #swap_space: {{ ansible_memtotal_mb|int * 2000000 }}
    swap_space: 1024000000

# @ToDo: Use swap device where possible
- name: set swap_file variable
  set_fact:
    swap_file: /mnt/swapfile.swap

- name: check if swap file exists
  stat:
    path: "{{ swap_file }}"
    get_attributes: False
    get_checksum:   False
    # @ToDo: Deprecate when we get to Ansible 2.5.x
    #get_md5:        False
    get_mime:       False
  register: swap_file_check

- import_tasks: file.yml
  when: not swap_file_check.stat.exists
