---
# @ToDo: Allow selection of alternate appname (low priority)

# Check for correct OS
-  fail: msg="Exiting as this deployment method currently only supports Debian"
   when: ansible_distribution != "Debian" # Doesn't include Ubuntu (ansible_os_family does))

# Run Debian-specific tasks
-  import_tasks: debian.yml
   when: ansible_distribution == "Debian" # Doesn't include Ubuntu (ansible_os_family does))

# Python Libraries, where we need a more recent version than that provided by the OS
- name: Install Reportlab # Want Percentage support
  pip: name=reportlab

- name: Install Shapely # Want Simplify enhancements
  pip: name=Shapely

- name: Install XLRD # XLS import support
  pip: name=xlrd

# Web2Py
- name: Create web2py user
  #user: name=web2py system=true
  command: adduser --system --disabled-password web2py

- name: Create web2py group
  group: name=web2py state=present

- name: Create symlink
  file: src=/home/web2py dest=/home/prod state=link owner=web2py group=web2py
  when: type == 'prod'

- name: Clone web2py # recursive by default
  git: repo=git://github.com/web2py/web2py.git dest=/home/{{ type}} version=cda35fd
  tags:
    - test
    - demo

# 2.14.6
#- name: Checkout stable release of Web2Py
#  command: git reset --hard cda35fd
#  args:
#    chdir: /home/{{ type }}
#  tags:
#    - test
#    - demo

- name: Configure PyDAL
  command: git submodule update --init --recursive
  args:
    chdir: /home/{{ type }}
  tags:
    - test
    - demo

- name: Copy wsgihandler
  command: cp -f /home/{{ type }}/handlers/wsgihandler.py /home/{{ type }}
  tags:
    - test
    - demo

- name: Copy routes.py
  copy: src=routes.py dest=/home/{{ type }}/routes.py
  tags:
    - test
    - demo

# matplotlib
# Only used by deprecated survey module
#- name: Create matplotlib directory
#  file: path=/home/{{ type }}/.matplotlib state=directory owner=web2py

#- name: Update wsgihandler.py
#  lineinfile: dest=/home/{{ type }}/wsgihandler.py
#              regexp=''
#              insertafter=EOF
#              line='os.environ["MPLCONFIGDIR"] = "/home/{{ type }}/.matplotlib"'

# - name: Edit matplotlibrc
#   lineinfile: dest=/etc/matplotlibrc state=present backref=yes regexp='backend      : TkAgg' line='backend      : Agg'

- name: Create symlink
  file: src=/home/{{ type }} dest=/root/{{ type }} state=link
  tags:
    - test
    - demo

# Eden
- name: Clone Eden
  git: repo=git://github.com/sahana/eden.git dest=/home/{{ type }}/applications/eden
  tags:
    - test
    - demo

- name: Fix permissions
  file: path=/home/{{item}} state=directory owner=web2py
  with_items:
    - "{{ type }}"
    - "{{ type }}/applications"
    - "{{ type }}/applications/admin/cache"
    - "{{ type }}/applications/admin/cron"
    - "{{ type }}/applications/admin/databases"
    - "{{ type }}/applications/admin/errors"
    - "{{ type }}/applications/admin/sessions"
    - "{{ type }}/applications/eden"
    - "{{ type }}/applications/eden/cache"
    - "{{ type }}/applications/eden/cron"
    - "{{ type }}/applications/eden/databases"
    - "{{ type }}/applications/eden/errors"
    - "{{ type }}/applications/eden/models"
    - "{{ type }}/applications/eden/sessions"
    - "{{ type }}/applications/eden/static/cache"
    - "{{ type }}/applications/eden/static/cache/chart"
    - "{{ type }}/applications/eden/static/fonts"
    - "{{ type }}/applications/eden/static/img/markers"
    - "{{ type }}/applications/eden/uploads"
    - "{{ type }}/applications/eden/uploads/gis_cache"
    - "{{ type }}/applications/eden/uploads/images"
    - "{{ type }}/applications/eden/uploads/tracks"
  tags:
    - test
    - demo

- name: Create symlink (eden in web2py)
  file: src=/home/{{ type }}/applications/eden dest=/home/{{ type }}/eden state=link
  tags:
    - test
    - demo

- name: Create symlink (eden in home)
  file: src=/home/{{ type }}/applications/eden dest=/root/eden state=link
  when: type == 'prod'
